=== tralfamadoriangithub/Dmitry_Anikeyenko/Task5/WebContent/xml/planesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/planesSchema"
	xmlns:tns="http://www.example.org/planesSchema" elementFormDefault="qualified">
	<element name="planes">
		<complexType>
			<sequence>
				<element name="plane" type="tns:Plane" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Plane">
		<sequence>
			<element name="model" type="string"></element>
			<element name="origin" type="string"></element>
			<element name="chars" type="tns:Chars"></element>
			<element name="parameters" type="tns:Parameters"></element>
			<element name="price" type="decimal"></element>
		</sequence>
		<attribute name="nrName" type="tns:NRName"></attribute>
	</complexType>

	<simpleType name="NRName">
		<restriction base="ID">
			<pattern value="[A-Z][a-zA-Z0-9-]*"></pattern>
		</restriction>
	</simpleType>

	<complexType name="Chars">
		<sequence>
			<element name="type">
				<simpleType>
					<restriction base="string">
						<enumeration value="fighter"></enumeration>
						<enumeration value="bomber"></enumeration>
						<enumeration value="reconnaissance"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="crew">
				<simpleType>
					<restriction base="integer">
						<enumeration value="1"></enumeration>
						<enumeration value="2"></enumeration>
					</restriction>
				</simpleType>
			</element>

			<element name="armament" minOccurs="0">
			<simpleType>
				<restriction base="integer">
					<minInclusive value="0"></minInclusive>
					<maxInclusive value="10"></maxInclusive>
				</restriction>
			</simpleType>
			</element>



			<element name="radar">
				<simpleType>
					<restriction base="string">
						<enumeration value="yes"></enumeration>
						<enumeration value="no"></enumeration>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>

	<attribute name="armamentAttribute">
		<simpleType>
			<restriction base="string">
				<enumeration value="yes"></enumeration>
				<enumeration value="no"></enumeration>
			</restriction>
		</simpleType>
	</attribute>

	<complexType name="Parameters">
		<all>
			<element name="width" type="decimal"></element>
			<element name="height" type="decimal"></element>
			<element name="length" type="decimal"></element>
		</all>
	</complexType>
</schema>

=== tralfamadoriangithub/Dmitry_Anikeyenko/Task5/planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:planes xmlns:tns="http://www.example.org/planesSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/planesSchema planesSchema.xsd ">
	
	<plane  nrName="Blackbird">
		<model>SR-71</model>
		<origin>USA</origin>
		<chars>
			<type>reconnaissance</type>
			<crew>2</crew>
			<radar>yes</radar>
		</chars>
		<parameters>
			<length>32.74</length>
			<width>16.94</width>
			<height>5.64</height>
		</parameters>
		<price>200000000</price>
	</plane>
	
	<plane nrName="Flanker-T">
		<model>SU-35</model>
		<origin>Russia</origin>
		<chars>
			<type>fighter</type>
			<crew>1</crew>
			<armament>10</armament>
			<radar>yes</radar>
		</chars>
		<parameters>
			<length>22.18</length>
			<width>14.75</width>
			<height>6.43</height>
		</parameters>
		<price>40000000</price>
	</plane>
	
	<plane nrName="Raptor">
		<model>F-22</model>
		<origin>USA</origin>
		<chars>
			<type>fighter</type>
			<crew>1</crew>
			<armament>8</armament>
			<radar>yes</radar>
		</chars>
		<parameters>
			<length>18.9</length>
			<width>13.56</width>
			<height>5.09</height>
		</parameters>
		<price>140000000</price>
	</plane>
</tns:planes>

=== tralfamadoriangithub/Dmitry_Anikeyenko/Task4/src/planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:planes xmlns:tns="http://www.example.org/planesSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/planesSchema planesSchema.xsd ">
	
	<tns:plane>
		<tns:model nrName="Blackbird">SR-71</tns:model>
		<tns:origin>USA</tns:origin>
		<tns:chars>
			<tns:type>reconnaissance</tns:type>
			<tns:crew>2</tns:crew>
			<tns:armament>0</tns:armament>
			<tns:radar>yes</tns:radar>
		</tns:chars>
		<tns:parameters>
			<tns:length>32.74</tns:length>
			<tns:width>16.94</tns:width>
			<tns:height>5.64</tns:height>
		</tns:parameters>
		<tns:price>200000000</tns:price>
	</tns:plane>
	
	<tns:plane>
		<tns:model nrName="Flanker-T">SU-35</tns:model>
		<tns:origin>Russia</tns:origin>
		<tns:chars>
			<tns:type>fighter</tns:type>
			<tns:crew>1</tns:crew>
			<tns:armament>10</tns:armament>
			<tns:radar>yes</tns:radar>
		</tns:chars>
		<tns:parameters>
			<tns:length>22.18</tns:length>
			<tns:width>14.75</tns:width>
			<tns:height>6.43</tns:height>
		</tns:parameters>
		<tns:price>40000000</tns:price>
	</tns:plane>
	
	<tns:plane>
		<tns:model nrName="Raptor">F-22</tns:model>
		<tns:origin>USA</tns:origin>
		<tns:chars>
			<tns:type>fighter</tns:type>
			<tns:crew>1</tns:crew>
			<tns:armament>8</tns:armament>
			<tns:radar>yes</tns:radar>
		</tns:chars>
		<tns:parameters>
			<tns:length>18.9</tns:length>
			<tns:width>13.56</tns:width>
			<tns:height>5.09</tns:height>
		</tns:parameters>
		<tns:price>140000000</tns:price>
	</tns:plane>
</tns:planes>
